apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 8080
  selector:
    app: cktk-get-ip-app2 
