apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  externalIPs:
    - 10.0.0.5
    - 10.0.0.6
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 8080
  selector:
    app: cktk-get-ip-app2 
