apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  completions: 10 
  parallelism: 5
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: post2slack-container
        image: chikutakureiwa2020/post2slack:v1
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred  
