apiVersion: v1
kind: Service
metadata:
  name: sample-lb
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 8080
      nodePort: 30000
  selector:
    app: cktk-get-ip-app2 
